### ISSUE TITLE
facebook version SDK to 4.8.+

### ISSUE THREAD

**Issue by sureshmvarma** [jeduan/cordova-plugin-facebook4#203]
Phonegapbuild issue using this plugin.

Failed to generate resource table for split ''
  	/project/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').

**Comment by Hirbod** [comment]
should be fixed in master

**Comment by sureshmvarma** [comment]
Issue not yet fixed getting following error in Phonegap build

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/android-sdk/build-tools/23.0.1/aapt package -f --no-crunch -I /android-sdk/platforms/android-22/android.jar -M /project/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /project/build/intermediates/res/debug -A /project/build/intermediates/assets/debug -m -J /project/build/generated/source/r/debug -F /project/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package com.conceptwaves.ilearn.triangles -0 apk --output-text-symbols /project/build/intermediates/symbols/debug
  Error Code:
  	1
  Output:
  	Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.
  	Failed to generate resource table for split ''
  	/project/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').

**Comment by fredgalvao** [comment]
I can confirm that error is fixed after upgrading to master, if and only if "master" meant anything after https://github.com/jeduan/cordova-plugin-facebook4/commit/6911f2d1b43a82254c78706bf03e314f3275a94f. Try reinstalling the plugin on your project, @sureshmvarma .
