### ISSUE TITLE
iOS13 beta returns an error when launching the login

### ISSUE THREAD

**Issue by monxas** [jeduan/cordova-plugin-facebook4#787]
**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Using this function immediately returns 

`Error logging into Facebook User cancelled.`

    `      this.fb.login(['public_profile', 'user_friends', 'email'])
        .then((res: FacebookLoginResponse) => {
          console.log('Logged into Facebook!', res);
          this.data = JSON.stringify(res);
        })
        .catch(e => console.log('Error logging into Facebook', e));
      });`

Without showing  any dialog

**Expected Behavior**

Show the login dialog

**Plugin version, OS, devices, etc**

ios13 beta 5, latest facebook plugin version

**Comment by peterpeterparker** [comment]
Just a guess, but that's either an iOS beta bug or Facebook SDK bug (as long as they don't publish a breaking change). Therefore nothin much so far we could do.

We could keep it open as reminder till iOS 13 will be published.

**Comment by aksmet** [comment]
They started fixing iOS 13 beta issues starting from the iOS SDK v5.2.0 release.

**Comment by peterpeterparker** [comment]
I just released a new version of the plugin (v6.0.0) which, furthermore than introducing Cocoapods for the iOS dependencies, also bump the Facebook SDK for iOS version to v5.2.3

According the FB release notes (https://github.com/facebook/facebook-objc-sdk/blob/master/CHANGELOG.md) it contains "Fixed Facebook Login on iOS 13 beta"

Therefore, could you plz update your plugin and tell the others if you still face the error or not?

**Comment by monxas** [comment]
@peterpeterparker Now I get a

`#import <FBSDKCoreKit/FBSDKCoreKit.h> 'FBSDKCoreKit/FBSDKCoreKit.h' file not found

in FacebookConnectPlugin.h 
`

**Comment by peterpeterparker** [comment]
@monxas cool happy to hear it is solved, thx for the test and feedback

**Comment by okanseremet** [comment]
removing and readding platforms didnt work for me. Problem still exists.

**Comment by ramaces** [comment]
i cannot update sdk from  4 to 5 on ionic 3 . is there another solution . i'm stuck looking 1 week for solution.
